### ISSUE TITLE
ModuleNotFoundError: No module named 'coloredlogs'

### ISSUE THREAD

**Issue by dodo325** [dodo325/mpm#1]
```python
C:\Users\markt>pip install mpm-core
Collecting mpm-core
  Using cached mpm-core-0.1.10.tar.gz (40 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\markt\anaconda3\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\markt\\AppData\\Local\\Temp\\pip-install-o1k3s159\\mpm-core\\setup.py'"'"'; __file__='"'"'C:\\Users\\markt\\AppData\\Local\\Temp\\pip-install-o1k3s159\\mpm-core\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\markt\AppData\Local\Temp\pip-install-o1k3s159\mpm-core\pip-egg-info'
         cwd: C:\Users\markt\AppData\Local\Temp\pip-install-o1k3s159\mpm-core\
    Complete output (13 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\markt\AppData\Local\Temp\pip-install-o1k3s159\mpm-core\setup.py", line 10, in <module>
        import mpm
      File "C:\Users\markt\AppData\Local\Temp\pip-install-o1k3s159\mpm-core\mpm\__init__.py", line 3, in <module>
        from mpm.shell import *
      File "C:\Users\markt\AppData\Local\Temp\pip-install-o1k3s159\mpm-core\mpm\shell\__init__.py", line 1, in <module>
        from mpm.shell.shells import (
      File "C:\Users\markt\AppData\Local\Temp\pip-install-o1k3s159\mpm-core\mpm\shell\shells.py", line 9, in <module>
        from mpm.core.logging import getLogger
      File "C:\Users\markt\AppData\Local\Temp\pip-install-o1k3s159\mpm-core\mpm\core\logging.py", line 4, in <module>
        import coloredlogs
    ModuleNotFoundError: No module named 'coloredlogs'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by dodo325** [comment]
For user fix:
```bash
pip install coloredlogs
```
